"""empty message

Revision ID: 35da34c651ad
Revises: 
Create Date: 2023-08-31 21:56:42.393236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35da34c651ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
